source 'https://rubygems.org'

gem 'nali'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use Uglifier as compressor for JavaScript client
gem 'uglifier'

# Use debugger
#gem 'debugger'
