source 'https://rubygems.org'

gem 'nali'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'

group :development, :test do

  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'

  # Use debugger
  #gem 'debugger'

end
